### ISSUE TITLE
Can't login with "admin" and no password. Please help!

### ISSUE THREAD

**Issue by CharlieMSU** [Mhynlo/rn-utorrent#1]
The default login of username/password admin/[blank] doesn't work. Please help!

**Comment by Mhynlo** [comment]
What port are you logging in?
The address should be `http://<nas_ip>:7574/gui/web/index.html`. That is the same address that is from the **Launch** button in the ReadyNAS admin UI.
I did notice the https is not very responsive with its current configuration.

Did you change the admin password in the uTorrent app?

**Comment by CharlieMSU** [comment]
Sorry for the delay in responding, your email got lost in the shuffle. To answer your question:
- ```
       The address you provided matches the one I’m using.
  ```
- ```
       No user and password have been changed as I have never been able to login in the first place.
  ```

Is there a way to reset something? From the get go, the default user and pass never worked.

I cant wait to use the app but I’m locked out. :)

Charlie Souza

 mailto:charliesouza@hotmail.com charliesouza@hotmail.com

**Comment by Mhynlo** [comment]
Have you tried removing and adding the utorrent add-on?

There is an option that you could possibly set the password in the _/apps/utorrent/apps-config/utserver.conf_: `admin_password:`

Here is the uTorrent config guide:
https://forum.utorrent.com/topic/73370-sample-utserverconfig-file/

**Comment by CharlieMSU** [comment]
Hello Mhynlo,

I've been using your utorrent client for ReadyNAS and I'm very pleased with it. However, I can't help but ask if there's a way to update the build to a more recent utorrent version. Has there been an update? Or is there a way to update any modules through the command line?

Thank you much,
Charlie

On Aug 16, 2016, at 1:06 AM, Mhynlo <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you tried removing and adding the utorrent add-on?

There is an option that you could possibly set the password in the /apps/utorrent/apps-config/utserver.conf: admin_password:

Here is the uTorrent config guide:
https://forum.utorrent.com/topic/73370-sample-utserverconfig-file/

**Comment by Mhynlo** [comment]
I am glad to hear the app is working well for you.
The uTorrent linux development is not very active over the past ~3 years.
https://forum.utorrent.com/topic/104522-is-%CE%BCtorrent-for-linux-abandoned/

I am keeping an eye out for updates from their forums for newer builds.
